Value_ptr logic_or(Value *, Value *);
Value_ptr logic_and(Value *, Value *);
Value_ptr logic_not(Value *);
Value_ptr eq(Value *, Value *);
Value_ptr ne(Value *, Value *);
Value_ptr lt(Value *, Value *);
Value_ptr le(Value *, Value *);
Value_ptr gt(Value *, Value *);
Value_ptr ge(Value *, Value *);
Value_ptr add(Value *, Value *);
Value_ptr subtract(Value *, Value *);
Value_ptr multiply(Value *, Value *);
Value_ptr divide(Value *, Value *);
Value_ptr floored_divide(Value *, Value *);
Value_ptr modulo(Value *, Value *);
Value_ptr negate(Value *);
Value_ptr power(Value *, Value *);
Value_ptr simple_index(Value *, Value *);
Value_ptr row_index(Value *, Value *);
Value_ptr column_index(Value *, Value *);
void assign(Value *, Value_ptr);
